/* Generated by Yosys 0.57+148 (git sha1 259bd6fb3, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:1.1-111.10" *)
module booth_multiplier(clk, rst_n, start, multiplicand, multiplier, done, product);
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:4.11-4.14" *)
  input clk;
  wire clk;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:5.11-5.16" *)
  input rst_n;
  wire rst_n;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:6.11-6.16" *)
  input start;
  wire start;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:7.19-7.31" *)
  input [7:0] multiplicand;
  wire [7:0] multiplicand;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:8.19-8.29" *)
  input [7:0] multiplier;
  wire [7:0] multiplier;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:9.16-9.20" *)
  output done;
  wire done;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:10.26-10.33" *)
  output [15:0] product;
  wire [15:0] product;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:65.5-110.8" *)
  wire [8:0] _000_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:65.5-110.8" *)
  wire _001_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:65.5-110.8" *)
  wire [4:0] _002_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:14.15-14.16" *)
  wire _003_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:14.15-14.16" *)
  wire _004_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:14.15-14.16" *)
  wire _005_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:14.15-14.16" *)
  wire _006_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:14.15-14.16" *)
  wire _007_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:14.15-14.16" *)
  wire _008_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:14.15-14.16" *)
  wire _009_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:14.15-14.16" *)
  wire _010_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:14.15-14.16" *)
  wire _011_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:15.17-15.18" *)
  wire _012_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:15.17-15.18" *)
  wire _013_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:15.17-15.18" *)
  wire _014_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:15.17-15.18" *)
  wire _015_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:15.17-15.18" *)
  wire _016_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:15.17-15.18" *)
  wire _017_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:15.17-15.18" *)
  wire _018_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:15.17-15.18" *)
  wire _019_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:16.15-16.16" *)
  wire _020_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:16.15-16.16" *)
  wire _021_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:16.15-16.16" *)
  wire _022_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:16.15-16.16" *)
  wire _023_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:16.15-16.16" *)
  wire _024_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:16.15-16.16" *)
  wire _025_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:16.15-16.16" *)
  wire _026_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:16.15-16.16" *)
  wire _027_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:16.15-16.16" *)
  wire _028_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:17.9-17.18" *)
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:18.15-18.20" *)
  wire _083_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:18.15-18.20" *)
  wire _084_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:18.15-18.20" *)
  wire _085_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:18.15-18.20" *)
  wire _086_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:18.15-18.20" *)
  wire _087_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:7.19-7.31" *)
  wire _088_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:7.19-7.31" *)
  wire _089_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:7.19-7.31" *)
  wire _090_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:7.19-7.31" *)
  wire _091_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:7.19-7.31" *)
  wire _092_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:7.19-7.31" *)
  wire _093_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:7.19-7.31" *)
  wire _094_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:7.19-7.31" *)
  wire _095_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:8.19-8.29" *)
  wire _096_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:8.19-8.29" *)
  wire _097_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:8.19-8.29" *)
  wire _098_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:8.19-8.29" *)
  wire _099_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:8.19-8.29" *)
  wire _100_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:8.19-8.29" *)
  wire _101_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:8.19-8.29" *)
  wire _102_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:8.19-8.29" *)
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:10.26-10.33" *)
  wire _224_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:10.26-10.33" *)
  wire _225_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:10.26-10.33" *)
  wire _226_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:10.26-10.33" *)
  wire _227_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:10.26-10.33" *)
  wire _228_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:10.26-10.33" *)
  wire _229_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:10.26-10.33" *)
  wire _230_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:10.26-10.33" *)
  wire _231_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:10.26-10.33" *)
  wire _232_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:10.26-10.33" *)
  wire _233_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:10.26-10.33" *)
  wire _234_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:10.26-10.33" *)
  wire _235_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:10.26-10.33" *)
  wire _236_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:10.26-10.33" *)
  wire _237_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:10.26-10.33" *)
  wire _238_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:10.26-10.33" *)
  wire _239_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:6.11-6.16" *)
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  wire _316_;
  wire _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire _321_;
  wire _322_;
  wire _323_;
  wire _324_;
  wire _325_;
  wire _326_;
  wire _327_;
  wire _328_;
  wire _329_;
  wire _330_;
  wire _331_;
  wire _332_;
  wire _333_;
  wire _334_;
  wire _335_;
  wire _336_;
  wire _337_;
  wire _338_;
  wire _339_;
  wire _340_;
  wire _341_;
  wire _342_;
  wire _343_;
  wire _344_;
  wire _345_;
  wire _346_;
  wire _347_;
  wire _348_;
  wire _349_;
  wire _350_;
  wire _351_;
  wire _352_;
  wire _353_;
  wire _354_;
  wire _355_;
  wire _356_;
  wire _357_;
  wire _358_;
  wire _359_;
  wire _360_;
  wire _361_;
  wire _362_;
  wire _363_;
  wire _364_;
  wire _365_;
  wire _366_;
  wire _367_;
  wire _368_;
  wire _369_;
  wire _370_;
  wire _371_;
  wire _372_;
  wire _373_;
  wire _374_;
  wire _375_;
  wire _376_;
  wire _377_;
  wire _378_;
  wire _379_;
  wire _380_;
  wire _381_;
  wire _382_;
  wire _383_;
  wire _384_;
  wire _385_;
  wire _386_;
  wire _387_;
  wire _388_;
  wire _389_;
  wire _390_;
  wire _391_;
  wire _392_;
  wire _393_;
  wire _394_;
  wire _395_;
  wire _396_;
  wire _397_;
  wire _398_;
  wire _399_;
  wire _400_;
  wire _401_;
  wire _402_;
  wire _403_;
  wire _404_;
  wire _405_;
  wire _406_;
  wire _407_;
  wire _408_;
  wire _409_;
  wire _410_;
  wire _411_;
  wire _412_;
  wire _413_;
  wire _414_;
  wire _415_;
  wire _416_;
  wire _417_;
  wire _418_;
  wire _419_;
  wire _420_;
  wire _421_;
  wire _422_;
  wire _423_;
  wire _424_;
  wire _425_;
  wire _426_;
  wire _427_;
  wire _428_;
  wire _429_;
  wire _430_;
  wire _431_;
  wire _432_;
  wire _433_;
  (* force_downto = 32'd1 *)
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:96.20-96.20|/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:76.13-108.20|/usr/local/bin/../share/yosys/techmap.v:576.21-576.22" *)
  wire [8:0] _434_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:14.15-14.16" *)
  wire [8:0] A;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:15.17-15.18" *)
  wire [7:0] M;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:16.15-16.16" *)
  wire [8:0] Q;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:17.9-17.18" *)
  wire Q_minus_1;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:18.15-18.20" *)
  wire [4:0] count;
  (* onehot = 32'd1 *)
  wire [4:0] state;
  sky130_fd_sc_hd__clkinv_1 _435_ (
    .A(_240_),
    .Y(_104_)
  );
  sky130_fd_sc_hd__clkinv_1 _436_ (
    .A(_021_),
    .Y(_105_)
  );
  sky130_fd_sc_hd__clkinv_1 _437_ (
    .A(_022_),
    .Y(_106_)
  );
  sky130_fd_sc_hd__clkinv_1 _438_ (
    .A(_023_),
    .Y(_107_)
  );
  sky130_fd_sc_hd__clkinv_1 _439_ (
    .A(_024_),
    .Y(_108_)
  );
  sky130_fd_sc_hd__clkinv_1 _440_ (
    .A(_025_),
    .Y(_109_)
  );
  sky130_fd_sc_hd__clkinv_1 _441_ (
    .A(_026_),
    .Y(_110_)
  );
  sky130_fd_sc_hd__clkinv_1 _442_ (
    .A(_027_),
    .Y(_111_)
  );
  sky130_fd_sc_hd__clkinv_1 _443_ (
    .A(_028_),
    .Y(_112_)
  );
  sky130_fd_sc_hd__and2_0 _444_ (
    .A(_241_),
    .B(_240_),
    .X(_031_)
  );
  sky130_fd_sc_hd__nor2_1 _445_ (
    .A(_084_),
    .B(_083_),
    .Y(_113_)
  );
  sky130_fd_sc_hd__nand2_1 _446_ (
    .A(_086_),
    .B(_113_),
    .Y(_114_)
  );
  sky130_fd_sc_hd__nor3_1 _447_ (
    .A(_085_),
    .B(_087_),
    .C(_114_),
    .Y(_115_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _448_ (
    .A(_243_),
    .SLEEP(_115_),
    .X(_032_)
  );
  sky130_fd_sc_hd__and2_0 _449_ (
    .A(_243_),
    .B(_115_),
    .X(_030_)
  );
  sky130_fd_sc_hd__a21o_1 _450_ (
    .A1(_241_),
    .A2(_104_),
    .B1(_242_),
    .X(_033_)
  );
  sky130_fd_sc_hd__nor2_1 _451_ (
    .A(_245_),
    .B(_244_),
    .Y(_116_)
  );
  sky130_fd_sc_hd__clkinv_1 _452_ (
    .A(_116_),
    .Y(_034_)
  );
  sky130_fd_sc_hd__nor2_1 _453_ (
    .A(_245_),
    .B(_083_),
    .Y(_117_)
  );
  sky130_fd_sc_hd__a21oi_1 _454_ (
    .A1(_083_),
    .A2(_034_),
    .B1(_117_),
    .Y(_035_)
  );
  sky130_fd_sc_hd__nand2_1 _455_ (
    .A(_084_),
    .B(_083_),
    .Y(_118_)
  );
  sky130_fd_sc_hd__a22oi_1 _456_ (
    .A1(_084_),
    .A2(_116_),
    .B1(_118_),
    .B2(_245_),
    .Y(_119_)
  );
  sky130_fd_sc_hd__nor2_1 _457_ (
    .A(_113_),
    .B(_119_),
    .Y(_036_)
  );
  sky130_fd_sc_hd__and4_1 _458_ (
    .A(_245_),
    .B(_084_),
    .C(_083_),
    .D(_085_),
    .X(_120_)
  );
  sky130_fd_sc_hd__nand2b_1 _459_ (
    .A_N(_245_),
    .B(_244_),
    .Y(_121_)
  );
  sky130_fd_sc_hd__a32oi_1 _460_ (
    .A1(_245_),
    .A2(_084_),
    .A3(_083_),
    .B1(_085_),
    .B2(_121_),
    .Y(_122_)
  );
  sky130_fd_sc_hd__nor2_1 _461_ (
    .A(_120_),
    .B(_122_),
    .Y(_037_)
  );
  sky130_fd_sc_hd__nor2_1 _462_ (
    .A(_086_),
    .B(_120_),
    .Y(_123_)
  );
  sky130_fd_sc_hd__nand2_1 _463_ (
    .A(_086_),
    .B(_120_),
    .Y(_124_)
  );
  sky130_fd_sc_hd__nand2_1 _464_ (
    .A(_121_),
    .B(_124_),
    .Y(_125_)
  );
  sky130_fd_sc_hd__nor2_1 _465_ (
    .A(_123_),
    .B(_125_),
    .Y(_038_)
  );
  sky130_fd_sc_hd__a21oi_1 _466_ (
    .A1(_086_),
    .A2(_120_),
    .B1(_087_),
    .Y(_126_)
  );
  sky130_fd_sc_hd__a21oi_1 _467_ (
    .A1(_087_),
    .A2(_125_),
    .B1(_126_),
    .Y(_039_)
  );
  sky130_fd_sc_hd__o22ai_1 _468_ (
    .A1(_020_),
    .A2(_034_),
    .B1(_121_),
    .B2(_096_),
    .Y(_127_)
  );
  sky130_fd_sc_hd__a21oi_1 _469_ (
    .A1(_245_),
    .A2(_105_),
    .B1(_127_),
    .Y(_040_)
  );
  sky130_fd_sc_hd__o22ai_1 _470_ (
    .A1(_021_),
    .A2(_034_),
    .B1(_121_),
    .B2(_097_),
    .Y(_128_)
  );
  sky130_fd_sc_hd__a21oi_1 _471_ (
    .A1(_245_),
    .A2(_106_),
    .B1(_128_),
    .Y(_041_)
  );
  sky130_fd_sc_hd__o22ai_1 _472_ (
    .A1(_022_),
    .A2(_034_),
    .B1(_121_),
    .B2(_098_),
    .Y(_129_)
  );
  sky130_fd_sc_hd__a21oi_1 _473_ (
    .A1(_245_),
    .A2(_107_),
    .B1(_129_),
    .Y(_042_)
  );
  sky130_fd_sc_hd__o22ai_1 _474_ (
    .A1(_023_),
    .A2(_034_),
    .B1(_121_),
    .B2(_099_),
    .Y(_130_)
  );
  sky130_fd_sc_hd__a21oi_1 _475_ (
    .A1(_245_),
    .A2(_108_),
    .B1(_130_),
    .Y(_043_)
  );
  sky130_fd_sc_hd__o22ai_1 _476_ (
    .A1(_024_),
    .A2(_034_),
    .B1(_121_),
    .B2(_100_),
    .Y(_131_)
  );
  sky130_fd_sc_hd__a21oi_1 _477_ (
    .A1(_245_),
    .A2(_109_),
    .B1(_131_),
    .Y(_044_)
  );
  sky130_fd_sc_hd__o22ai_1 _478_ (
    .A1(_025_),
    .A2(_034_),
    .B1(_121_),
    .B2(_101_),
    .Y(_132_)
  );
  sky130_fd_sc_hd__a21oi_1 _479_ (
    .A1(_245_),
    .A2(_110_),
    .B1(_132_),
    .Y(_045_)
  );
  sky130_fd_sc_hd__o22ai_1 _480_ (
    .A1(_026_),
    .A2(_034_),
    .B1(_121_),
    .B2(_102_),
    .Y(_133_)
  );
  sky130_fd_sc_hd__a21oi_1 _481_ (
    .A1(_245_),
    .A2(_111_),
    .B1(_133_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__o22ai_1 _482_ (
    .A1(_027_),
    .A2(_034_),
    .B1(_121_),
    .B2(_103_),
    .Y(_134_)
  );
  sky130_fd_sc_hd__a21oi_1 _483_ (
    .A1(_245_),
    .A2(_112_),
    .B1(_134_),
    .Y(_047_)
  );
  sky130_fd_sc_hd__nand2_1 _484_ (
    .A(_245_),
    .B(_003_),
    .Y(_135_)
  );
  sky130_fd_sc_hd__o21ai_0 _485_ (
    .A1(_112_),
    .A2(_034_),
    .B1(_135_),
    .Y(_048_)
  );
  sky130_fd_sc_hd__nor2_1 _486_ (
    .A(_242_),
    .B(_224_),
    .Y(_136_)
  );
  sky130_fd_sc_hd__a21oi_1 _487_ (
    .A1(_242_),
    .A2(_105_),
    .B1(_136_),
    .Y(_049_)
  );
  sky130_fd_sc_hd__nor2_1 _488_ (
    .A(_242_),
    .B(_231_),
    .Y(_137_)
  );
  sky130_fd_sc_hd__a21oi_1 _489_ (
    .A1(_242_),
    .A2(_106_),
    .B1(_137_),
    .Y(_050_)
  );
  sky130_fd_sc_hd__nor2_1 _490_ (
    .A(_242_),
    .B(_232_),
    .Y(_138_)
  );
  sky130_fd_sc_hd__a21oi_1 _491_ (
    .A1(_242_),
    .A2(_107_),
    .B1(_138_),
    .Y(_051_)
  );
  sky130_fd_sc_hd__nor2_1 _492_ (
    .A(_242_),
    .B(_233_),
    .Y(_139_)
  );
  sky130_fd_sc_hd__a21oi_1 _493_ (
    .A1(_242_),
    .A2(_108_),
    .B1(_139_),
    .Y(_052_)
  );
  sky130_fd_sc_hd__nor2_1 _494_ (
    .A(_242_),
    .B(_234_),
    .Y(_140_)
  );
  sky130_fd_sc_hd__a21oi_1 _495_ (
    .A1(_242_),
    .A2(_109_),
    .B1(_140_),
    .Y(_053_)
  );
  sky130_fd_sc_hd__nor2_1 _496_ (
    .A(_242_),
    .B(_235_),
    .Y(_141_)
  );
  sky130_fd_sc_hd__a21oi_1 _497_ (
    .A1(_242_),
    .A2(_110_),
    .B1(_141_),
    .Y(_054_)
  );
  sky130_fd_sc_hd__nor2_1 _498_ (
    .A(_242_),
    .B(_236_),
    .Y(_142_)
  );
  sky130_fd_sc_hd__a21oi_1 _499_ (
    .A1(_242_),
    .A2(_111_),
    .B1(_142_),
    .Y(_055_)
  );
  sky130_fd_sc_hd__nor2_1 _500_ (
    .A(_242_),
    .B(_237_),
    .Y(_143_)
  );
  sky130_fd_sc_hd__a21oi_1 _501_ (
    .A1(_242_),
    .A2(_112_),
    .B1(_143_),
    .Y(_056_)
  );
  sky130_fd_sc_hd__mux2_1 _502_ (
    .A0(_238_),
    .A1(_003_),
    .S(_242_),
    .X(_057_)
  );
  sky130_fd_sc_hd__mux2_1 _503_ (
    .A0(_239_),
    .A1(_004_),
    .S(_242_),
    .X(_058_)
  );
  sky130_fd_sc_hd__mux2_1 _504_ (
    .A0(_225_),
    .A1(_005_),
    .S(_242_),
    .X(_059_)
  );
  sky130_fd_sc_hd__mux2_1 _505_ (
    .A0(_226_),
    .A1(_006_),
    .S(_242_),
    .X(_060_)
  );
  sky130_fd_sc_hd__mux2_1 _506_ (
    .A0(_227_),
    .A1(_007_),
    .S(_242_),
    .X(_061_)
  );
  sky130_fd_sc_hd__mux2_1 _507_ (
    .A0(_228_),
    .A1(_008_),
    .S(_242_),
    .X(_062_)
  );
  sky130_fd_sc_hd__mux2_1 _508_ (
    .A0(_229_),
    .A1(_009_),
    .S(_242_),
    .X(_063_)
  );
  sky130_fd_sc_hd__mux2_1 _509_ (
    .A0(_230_),
    .A1(_010_),
    .S(_242_),
    .X(_064_)
  );
  sky130_fd_sc_hd__nand2b_1 _510_ (
    .A_N(_029_),
    .B(_020_),
    .Y(_144_)
  );
  sky130_fd_sc_hd__nand2b_1 _511_ (
    .A_N(_020_),
    .B(_029_),
    .Y(_145_)
  );
  sky130_fd_sc_hd__nor3_1 _512_ (
    .A(_243_),
    .B(_245_),
    .C(_244_),
    .Y(_146_)
  );
  sky130_fd_sc_hd__a31oi_1 _513_ (
    .A1(_243_),
    .A2(_144_),
    .A3(_145_),
    .B1(_146_),
    .Y(_147_)
  );
  sky130_fd_sc_hd__nand2b_1 _514_ (
    .A_N(_003_),
    .B(_012_),
    .Y(_148_)
  );
  sky130_fd_sc_hd__xor2_1 _515_ (
    .A(_003_),
    .B(_012_),
    .X(_149_)
  );
  sky130_fd_sc_hd__a22oi_1 _516_ (
    .A1(_245_),
    .A2(_004_),
    .B1(_149_),
    .B2(_243_),
    .Y(_150_)
  );
  sky130_fd_sc_hd__nor2_1 _517_ (
    .A(_003_),
    .B(_147_),
    .Y(_151_)
  );
  sky130_fd_sc_hd__a21oi_1 _518_ (
    .A1(_147_),
    .A2(_150_),
    .B1(_151_),
    .Y(_065_)
  );
  sky130_fd_sc_hd__nand2_1 _519_ (
    .A(_012_),
    .B(_144_),
    .Y(_152_)
  );
  sky130_fd_sc_hd__xor2_1 _520_ (
    .A(_013_),
    .B(_152_),
    .X(_153_)
  );
  sky130_fd_sc_hd__xor2_1 _521_ (
    .A(_004_),
    .B(_153_),
    .X(_154_)
  );
  sky130_fd_sc_hd__o21ai_0 _522_ (
    .A1(_148_),
    .A2(_154_),
    .B1(_243_),
    .Y(_155_)
  );
  sky130_fd_sc_hd__a21oi_1 _523_ (
    .A1(_148_),
    .A2(_154_),
    .B1(_155_),
    .Y(_156_)
  );
  sky130_fd_sc_hd__nand2_1 _524_ (
    .A(_245_),
    .B(_005_),
    .Y(_157_)
  );
  sky130_fd_sc_hd__nand2_1 _525_ (
    .A(_147_),
    .B(_157_),
    .Y(_158_)
  );
  sky130_fd_sc_hd__o22a_1 _526_ (
    .A1(_004_),
    .A2(_147_),
    .B1(_156_),
    .B2(_158_),
    .X(_066_)
  );
  sky130_fd_sc_hd__maj3_1 _527_ (
    .A(_004_),
    .B(_148_),
    .C(_153_),
    .X(_159_)
  );
  sky130_fd_sc_hd__o21ai_0 _528_ (
    .A1(_012_),
    .A2(_013_),
    .B1(_144_),
    .Y(_160_)
  );
  sky130_fd_sc_hd__xor2_1 _529_ (
    .A(_014_),
    .B(_160_),
    .X(_161_)
  );
  sky130_fd_sc_hd__xor2_1 _530_ (
    .A(_005_),
    .B(_161_),
    .X(_162_)
  );
  sky130_fd_sc_hd__xor2_1 _531_ (
    .A(_159_),
    .B(_162_),
    .X(_163_)
  );
  sky130_fd_sc_hd__nand2_1 _532_ (
    .A(_243_),
    .B(_163_),
    .Y(_164_)
  );
  sky130_fd_sc_hd__nand2_1 _533_ (
    .A(_245_),
    .B(_006_),
    .Y(_165_)
  );
  sky130_fd_sc_hd__nor2_1 _534_ (
    .A(_005_),
    .B(_147_),
    .Y(_166_)
  );
  sky130_fd_sc_hd__a31oi_1 _535_ (
    .A1(_147_),
    .A2(_164_),
    .A3(_165_),
    .B1(_166_),
    .Y(_067_)
  );
  sky130_fd_sc_hd__nor2_1 _536_ (
    .A(_006_),
    .B(_147_),
    .Y(_167_)
  );
  sky130_fd_sc_hd__maj3_1 _537_ (
    .A(_005_),
    .B(_159_),
    .C(_161_),
    .X(_168_)
  );
  sky130_fd_sc_hd__o31ai_1 _538_ (
    .A1(_012_),
    .A2(_013_),
    .A3(_014_),
    .B1(_144_),
    .Y(_169_)
  );
  sky130_fd_sc_hd__xor2_1 _539_ (
    .A(_015_),
    .B(_169_),
    .X(_170_)
  );
  sky130_fd_sc_hd__nand2_1 _540_ (
    .A(_006_),
    .B(_170_),
    .Y(_171_)
  );
  sky130_fd_sc_hd__clkinv_1 _541_ (
    .A(_171_),
    .Y(_172_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _542_ (
    .A(_006_),
    .SLEEP(_170_),
    .X(_173_)
  );
  sky130_fd_sc_hd__nand3_1 _543_ (
    .A(_168_),
    .B(_171_),
    .C(_173_),
    .Y(_174_)
  );
  sky130_fd_sc_hd__a21o_1 _544_ (
    .A1(_171_),
    .A2(_173_),
    .B1(_168_),
    .X(_175_)
  );
  sky130_fd_sc_hd__nand3_1 _545_ (
    .A(_243_),
    .B(_174_),
    .C(_175_),
    .Y(_176_)
  );
  sky130_fd_sc_hd__nand2_1 _546_ (
    .A(_245_),
    .B(_007_),
    .Y(_177_)
  );
  sky130_fd_sc_hd__a31oi_1 _547_ (
    .A1(_147_),
    .A2(_176_),
    .A3(_177_),
    .B1(_167_),
    .Y(_068_)
  );
  sky130_fd_sc_hd__nor2_1 _548_ (
    .A(_007_),
    .B(_147_),
    .Y(_178_)
  );
  sky130_fd_sc_hd__o41a_1 _549_ (
    .A1(_012_),
    .A2(_013_),
    .A3(_014_),
    .A4(_015_),
    .B1(_144_),
    .X(_179_)
  );
  sky130_fd_sc_hd__xnor2_1 _550_ (
    .A(_016_),
    .B(_179_),
    .Y(_180_)
  );
  sky130_fd_sc_hd__nand2_1 _551_ (
    .A(_007_),
    .B(_180_),
    .Y(_181_)
  );
  sky130_fd_sc_hd__xor2_1 _552_ (
    .A(_007_),
    .B(_180_),
    .X(_182_)
  );
  sky130_fd_sc_hd__o21ai_0 _553_ (
    .A1(_168_),
    .A2(_172_),
    .B1(_173_),
    .Y(_183_)
  );
  sky130_fd_sc_hd__o211ai_1 _554_ (
    .A1(_168_),
    .A2(_172_),
    .B1(_173_),
    .C1(_182_),
    .Y(_184_)
  );
  sky130_fd_sc_hd__xnor2_1 _555_ (
    .A(_182_),
    .B(_183_),
    .Y(_185_)
  );
  sky130_fd_sc_hd__nand2_1 _556_ (
    .A(_243_),
    .B(_185_),
    .Y(_186_)
  );
  sky130_fd_sc_hd__nand2_1 _557_ (
    .A(_245_),
    .B(_008_),
    .Y(_187_)
  );
  sky130_fd_sc_hd__a31oi_1 _558_ (
    .A1(_147_),
    .A2(_186_),
    .A3(_187_),
    .B1(_178_),
    .Y(_069_)
  );
  sky130_fd_sc_hd__nor2_1 _559_ (
    .A(_008_),
    .B(_147_),
    .Y(_188_)
  );
  sky130_fd_sc_hd__a21oi_1 _560_ (
    .A1(_016_),
    .A2(_144_),
    .B1(_179_),
    .Y(_189_)
  );
  sky130_fd_sc_hd__xnor2_1 _561_ (
    .A(_017_),
    .B(_189_),
    .Y(_190_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _562_ (
    .A(_008_),
    .SLEEP(_190_),
    .X(_191_)
  );
  sky130_fd_sc_hd__xor2_1 _563_ (
    .A(_008_),
    .B(_190_),
    .X(_192_)
  );
  sky130_fd_sc_hd__nand3_1 _564_ (
    .A(_181_),
    .B(_184_),
    .C(_192_),
    .Y(_193_)
  );
  sky130_fd_sc_hd__a21oi_1 _565_ (
    .A1(_181_),
    .A2(_184_),
    .B1(_192_),
    .Y(_194_)
  );
  sky130_fd_sc_hd__nand3b_1 _566_ (
    .A_N(_194_),
    .B(_243_),
    .C(_193_),
    .Y(_195_)
  );
  sky130_fd_sc_hd__nand2_1 _567_ (
    .A(_009_),
    .B(_245_),
    .Y(_196_)
  );
  sky130_fd_sc_hd__a31oi_1 _568_ (
    .A1(_147_),
    .A2(_195_),
    .A3(_196_),
    .B1(_188_),
    .Y(_070_)
  );
  sky130_fd_sc_hd__nor2_1 _569_ (
    .A(_009_),
    .B(_147_),
    .Y(_197_)
  );
  sky130_fd_sc_hd__o31ai_1 _570_ (
    .A1(_017_),
    .A2(_016_),
    .A3(_179_),
    .B1(_144_),
    .Y(_198_)
  );
  sky130_fd_sc_hd__xor2_1 _571_ (
    .A(_018_),
    .B(_198_),
    .X(_199_)
  );
  sky130_fd_sc_hd__nand2_1 _572_ (
    .A(_009_),
    .B(_199_),
    .Y(_200_)
  );
  sky130_fd_sc_hd__xor2_1 _573_ (
    .A(_009_),
    .B(_199_),
    .X(_201_)
  );
  sky130_fd_sc_hd__o21ai_0 _574_ (
    .A1(_191_),
    .A2(_194_),
    .B1(_201_),
    .Y(_202_)
  );
  sky130_fd_sc_hd__or3_1 _575_ (
    .A(_191_),
    .B(_194_),
    .C(_201_),
    .X(_203_)
  );
  sky130_fd_sc_hd__nand3_1 _576_ (
    .A(_243_),
    .B(_202_),
    .C(_203_),
    .Y(_204_)
  );
  sky130_fd_sc_hd__nand2_1 _577_ (
    .A(_245_),
    .B(_010_),
    .Y(_205_)
  );
  sky130_fd_sc_hd__a31oi_1 _578_ (
    .A1(_147_),
    .A2(_204_),
    .A3(_205_),
    .B1(_197_),
    .Y(_071_)
  );
  sky130_fd_sc_hd__nor2_1 _579_ (
    .A(_010_),
    .B(_147_),
    .Y(_206_)
  );
  sky130_fd_sc_hd__nand2_1 _580_ (
    .A(_018_),
    .B(_144_),
    .Y(_207_)
  );
  sky130_fd_sc_hd__nand2_1 _581_ (
    .A(_198_),
    .B(_207_),
    .Y(_208_)
  );
  sky130_fd_sc_hd__xnor2_1 _582_ (
    .A(_019_),
    .B(_208_),
    .Y(_209_)
  );
  sky130_fd_sc_hd__nand2_1 _583_ (
    .A(_010_),
    .B(_209_),
    .Y(_210_)
  );
  sky130_fd_sc_hd__xnor2_1 _584_ (
    .A(_010_),
    .B(_209_),
    .Y(_211_)
  );
  sky130_fd_sc_hd__nand3_1 _585_ (
    .A(_200_),
    .B(_202_),
    .C(_211_),
    .Y(_212_)
  );
  sky130_fd_sc_hd__a21o_1 _586_ (
    .A1(_200_),
    .A2(_202_),
    .B1(_211_),
    .X(_213_)
  );
  sky130_fd_sc_hd__nand3_1 _587_ (
    .A(_243_),
    .B(_212_),
    .C(_213_),
    .Y(_214_)
  );
  sky130_fd_sc_hd__nand2_1 _588_ (
    .A(_245_),
    .B(_011_),
    .Y(_215_)
  );
  sky130_fd_sc_hd__a31oi_1 _589_ (
    .A1(_147_),
    .A2(_214_),
    .A3(_215_),
    .B1(_206_),
    .Y(_072_)
  );
  sky130_fd_sc_hd__a31oi_1 _590_ (
    .A1(_243_),
    .A2(_144_),
    .A3(_145_),
    .B1(_245_),
    .Y(_216_)
  );
  sky130_fd_sc_hd__o21ai_0 _591_ (
    .A1(_243_),
    .A2(_244_),
    .B1(_216_),
    .Y(_217_)
  );
  sky130_fd_sc_hd__nand2_1 _592_ (
    .A(_011_),
    .B(_217_),
    .Y(_218_)
  );
  sky130_fd_sc_hd__a21oi_1 _593_ (
    .A1(_019_),
    .A2(_144_),
    .B1(_208_),
    .Y(_219_)
  );
  sky130_fd_sc_hd__xnor2_1 _594_ (
    .A(_011_),
    .B(_219_),
    .Y(_220_)
  );
  sky130_fd_sc_hd__and3_1 _595_ (
    .A(_210_),
    .B(_213_),
    .C(_220_),
    .X(_221_)
  );
  sky130_fd_sc_hd__a21oi_1 _596_ (
    .A1(_210_),
    .A2(_213_),
    .B1(_220_),
    .Y(_222_)
  );
  sky130_fd_sc_hd__nand2_1 _597_ (
    .A(_243_),
    .B(_216_),
    .Y(_223_)
  );
  sky130_fd_sc_hd__o31ai_1 _598_ (
    .A1(_221_),
    .A2(_222_),
    .A3(_223_),
    .B1(_218_),
    .Y(_073_)
  );
  sky130_fd_sc_hd__mux2_1 _599_ (
    .A0(_012_),
    .A1(_088_),
    .S(_244_),
    .X(_074_)
  );
  sky130_fd_sc_hd__mux2_1 _600_ (
    .A0(_013_),
    .A1(_089_),
    .S(_244_),
    .X(_075_)
  );
  sky130_fd_sc_hd__mux2_1 _601_ (
    .A0(_014_),
    .A1(_090_),
    .S(_244_),
    .X(_076_)
  );
  sky130_fd_sc_hd__mux2_1 _602_ (
    .A0(_015_),
    .A1(_091_),
    .S(_244_),
    .X(_077_)
  );
  sky130_fd_sc_hd__mux2_1 _603_ (
    .A0(_016_),
    .A1(_092_),
    .S(_244_),
    .X(_078_)
  );
  sky130_fd_sc_hd__mux2_1 _604_ (
    .A0(_017_),
    .A1(_093_),
    .S(_244_),
    .X(_079_)
  );
  sky130_fd_sc_hd__mux2_1 _605_ (
    .A0(_018_),
    .A1(_094_),
    .S(_244_),
    .X(_080_)
  );
  sky130_fd_sc_hd__mux2_1 _606_ (
    .A0(_019_),
    .A1(_095_),
    .S(_244_),
    .X(_081_)
  );
  sky130_fd_sc_hd__a22o_1 _607_ (
    .A1(_245_),
    .A2(_020_),
    .B1(_029_),
    .B2(_116_),
    .X(_082_)
  );
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:65.5-110.8" *)
  sky130_fd_sc_hd__dfrtp_1 _608_ (
    .CLK(clk),
    .D(_386_),
    .Q(count[0]),
    .RESET_B(rst_n)
  );
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:65.5-110.8" *)
  sky130_fd_sc_hd__dfrtp_1 _609_ (
    .CLK(clk),
    .D(_387_),
    .Q(count[1]),
    .RESET_B(rst_n)
  );
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:65.5-110.8" *)
  sky130_fd_sc_hd__dfrtp_1 _610_ (
    .CLK(clk),
    .D(_388_),
    .Q(count[2]),
    .RESET_B(rst_n)
  );
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:65.5-110.8" *)
  sky130_fd_sc_hd__dfrtp_1 _611_ (
    .CLK(clk),
    .D(_389_),
    .Q(count[3]),
    .RESET_B(rst_n)
  );
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:65.5-110.8" *)
  sky130_fd_sc_hd__dfrtp_1 _612_ (
    .CLK(clk),
    .D(_390_),
    .Q(count[4]),
    .RESET_B(rst_n)
  );
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:65.5-110.8" *)
  sky130_fd_sc_hd__dfrtp_1 _613_ (
    .CLK(clk),
    .D(_391_),
    .Q(Q[0]),
    .RESET_B(rst_n)
  );
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:65.5-110.8" *)
  sky130_fd_sc_hd__dfrtp_1 _614_ (
    .CLK(clk),
    .D(_392_),
    .Q(Q[1]),
    .RESET_B(rst_n)
  );
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:65.5-110.8" *)
  sky130_fd_sc_hd__dfrtp_1 _615_ (
    .CLK(clk),
    .D(_393_),
    .Q(Q[2]),
    .RESET_B(rst_n)
  );
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:65.5-110.8" *)
  sky130_fd_sc_hd__dfrtp_1 _616_ (
    .CLK(clk),
    .D(_394_),
    .Q(Q[3]),
    .RESET_B(rst_n)
  );
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:65.5-110.8" *)
  sky130_fd_sc_hd__dfrtp_1 _617_ (
    .CLK(clk),
    .D(_395_),
    .Q(Q[4]),
    .RESET_B(rst_n)
  );
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:65.5-110.8" *)
  sky130_fd_sc_hd__dfrtp_1 _618_ (
    .CLK(clk),
    .D(_396_),
    .Q(Q[5]),
    .RESET_B(rst_n)
  );
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:65.5-110.8" *)
  sky130_fd_sc_hd__dfrtp_1 _619_ (
    .CLK(clk),
    .D(_397_),
    .Q(Q[6]),
    .RESET_B(rst_n)
  );
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:65.5-110.8" *)
  sky130_fd_sc_hd__dfrtp_1 _620_ (
    .CLK(clk),
    .D(_398_),
    .Q(Q[7]),
    .RESET_B(rst_n)
  );
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:65.5-110.8" *)
  sky130_fd_sc_hd__dfrtp_1 _621_ (
    .CLK(clk),
    .D(_399_),
    .Q(Q[8]),
    .RESET_B(rst_n)
  );
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:65.5-110.8" *)
  sky130_fd_sc_hd__dfrtp_1 _622_ (
    .CLK(clk),
    .D(state[1]),
    .Q(done),
    .RESET_B(rst_n)
  );
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:65.5-110.8" *)
  sky130_fd_sc_hd__dfrtp_1 _623_ (
    .CLK(clk),
    .D(_400_),
    .Q(product[0]),
    .RESET_B(rst_n)
  );
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:65.5-110.8" *)
  sky130_fd_sc_hd__dfrtp_1 _624_ (
    .CLK(clk),
    .D(_401_),
    .Q(product[1]),
    .RESET_B(rst_n)
  );
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:65.5-110.8" *)
  sky130_fd_sc_hd__dfrtp_1 _625_ (
    .CLK(clk),
    .D(_402_),
    .Q(product[2]),
    .RESET_B(rst_n)
  );
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:65.5-110.8" *)
  sky130_fd_sc_hd__dfrtp_1 _626_ (
    .CLK(clk),
    .D(_403_),
    .Q(product[3]),
    .RESET_B(rst_n)
  );
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:65.5-110.8" *)
  sky130_fd_sc_hd__dfrtp_1 _627_ (
    .CLK(clk),
    .D(_404_),
    .Q(product[4]),
    .RESET_B(rst_n)
  );
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:65.5-110.8" *)
  sky130_fd_sc_hd__dfrtp_1 _628_ (
    .CLK(clk),
    .D(_405_),
    .Q(product[5]),
    .RESET_B(rst_n)
  );
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:65.5-110.8" *)
  sky130_fd_sc_hd__dfrtp_1 _629_ (
    .CLK(clk),
    .D(_406_),
    .Q(product[6]),
    .RESET_B(rst_n)
  );
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:65.5-110.8" *)
  sky130_fd_sc_hd__dfrtp_1 _630_ (
    .CLK(clk),
    .D(_407_),
    .Q(product[7]),
    .RESET_B(rst_n)
  );
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:65.5-110.8" *)
  sky130_fd_sc_hd__dfrtp_1 _631_ (
    .CLK(clk),
    .D(_408_),
    .Q(product[8]),
    .RESET_B(rst_n)
  );
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:65.5-110.8" *)
  sky130_fd_sc_hd__dfrtp_1 _632_ (
    .CLK(clk),
    .D(_409_),
    .Q(product[9]),
    .RESET_B(rst_n)
  );
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:65.5-110.8" *)
  sky130_fd_sc_hd__dfrtp_1 _633_ (
    .CLK(clk),
    .D(_410_),
    .Q(product[10]),
    .RESET_B(rst_n)
  );
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:65.5-110.8" *)
  sky130_fd_sc_hd__dfrtp_1 _634_ (
    .CLK(clk),
    .D(_411_),
    .Q(product[11]),
    .RESET_B(rst_n)
  );
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:65.5-110.8" *)
  sky130_fd_sc_hd__dfrtp_1 _635_ (
    .CLK(clk),
    .D(_412_),
    .Q(product[12]),
    .RESET_B(rst_n)
  );
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:65.5-110.8" *)
  sky130_fd_sc_hd__dfrtp_1 _636_ (
    .CLK(clk),
    .D(_413_),
    .Q(product[13]),
    .RESET_B(rst_n)
  );
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:65.5-110.8" *)
  sky130_fd_sc_hd__dfrtp_1 _637_ (
    .CLK(clk),
    .D(_414_),
    .Q(product[14]),
    .RESET_B(rst_n)
  );
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:65.5-110.8" *)
  sky130_fd_sc_hd__dfrtp_1 _638_ (
    .CLK(clk),
    .D(_415_),
    .Q(product[15]),
    .RESET_B(rst_n)
  );
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:65.5-110.8" *)
  sky130_fd_sc_hd__dfrtp_1 _639_ (
    .CLK(clk),
    .D(_416_),
    .Q(A[0]),
    .RESET_B(rst_n)
  );
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:65.5-110.8" *)
  sky130_fd_sc_hd__dfrtp_1 _640_ (
    .CLK(clk),
    .D(_417_),
    .Q(A[1]),
    .RESET_B(rst_n)
  );
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:65.5-110.8" *)
  sky130_fd_sc_hd__dfrtp_1 _641_ (
    .CLK(clk),
    .D(_418_),
    .Q(A[2]),
    .RESET_B(rst_n)
  );
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:65.5-110.8" *)
  sky130_fd_sc_hd__dfrtp_1 _642_ (
    .CLK(clk),
    .D(_419_),
    .Q(A[3]),
    .RESET_B(rst_n)
  );
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:65.5-110.8" *)
  sky130_fd_sc_hd__dfrtp_1 _643_ (
    .CLK(clk),
    .D(_420_),
    .Q(A[4]),
    .RESET_B(rst_n)
  );
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:65.5-110.8" *)
  sky130_fd_sc_hd__dfrtp_1 _644_ (
    .CLK(clk),
    .D(_421_),
    .Q(A[5]),
    .RESET_B(rst_n)
  );
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:65.5-110.8" *)
  sky130_fd_sc_hd__dfrtp_1 _645_ (
    .CLK(clk),
    .D(_422_),
    .Q(A[6]),
    .RESET_B(rst_n)
  );
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:65.5-110.8" *)
  sky130_fd_sc_hd__dfrtp_1 _646_ (
    .CLK(clk),
    .D(_423_),
    .Q(A[7]),
    .RESET_B(rst_n)
  );
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:65.5-110.8" *)
  sky130_fd_sc_hd__dfrtp_1 _647_ (
    .CLK(clk),
    .D(_424_),
    .Q(A[8]),
    .RESET_B(rst_n)
  );
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:65.5-110.8" *)
  sky130_fd_sc_hd__dfrtp_1 _648_ (
    .CLK(clk),
    .D(_425_),
    .Q(M[0]),
    .RESET_B(rst_n)
  );
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:65.5-110.8" *)
  sky130_fd_sc_hd__dfrtp_1 _649_ (
    .CLK(clk),
    .D(_426_),
    .Q(M[1]),
    .RESET_B(rst_n)
  );
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:65.5-110.8" *)
  sky130_fd_sc_hd__dfrtp_1 _650_ (
    .CLK(clk),
    .D(_427_),
    .Q(M[2]),
    .RESET_B(rst_n)
  );
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:65.5-110.8" *)
  sky130_fd_sc_hd__dfrtp_1 _651_ (
    .CLK(clk),
    .D(_428_),
    .Q(M[3]),
    .RESET_B(rst_n)
  );
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:65.5-110.8" *)
  sky130_fd_sc_hd__dfrtp_1 _652_ (
    .CLK(clk),
    .D(_429_),
    .Q(M[4]),
    .RESET_B(rst_n)
  );
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:65.5-110.8" *)
  sky130_fd_sc_hd__dfrtp_1 _653_ (
    .CLK(clk),
    .D(_430_),
    .Q(M[5]),
    .RESET_B(rst_n)
  );
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:65.5-110.8" *)
  sky130_fd_sc_hd__dfrtp_1 _654_ (
    .CLK(clk),
    .D(_431_),
    .Q(M[6]),
    .RESET_B(rst_n)
  );
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:65.5-110.8" *)
  sky130_fd_sc_hd__dfrtp_1 _655_ (
    .CLK(clk),
    .D(_432_),
    .Q(M[7]),
    .RESET_B(rst_n)
  );
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/booth_multiplier.v:65.5-110.8" *)
  sky130_fd_sc_hd__dfrtp_1 _656_ (
    .CLK(clk),
    .D(_433_),
    .Q(Q_minus_1),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfstp_2 _657_ (
    .CLK(clk),
    .D(_249_),
    .Q(state[0]),
    .SET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _658_ (
    .CLK(clk),
    .D(_246_),
    .Q(state[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _659_ (
    .CLK(clk),
    .D(_250_),
    .Q(state[2]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _660_ (
    .CLK(clk),
    .D(_247_),
    .Q(state[3]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _661_ (
    .CLK(clk),
    .D(_248_),
    .Q(state[4]),
    .RESET_B(rst_n)
  );
  assign _243_ = state[2];
  assign _009_ = A[6];
  assign _245_ = state[4];
  assign _017_ = M[5];
  assign _016_ = M[4];
  assign _008_ = A[5];
  assign _007_ = A[4];
  assign _010_ = A[7];
  assign _018_ = M[6];
  assign _011_ = A[8];
  assign _019_ = M[7];
  assign _241_ = state[0];
  assign _240_ = start;
  assign _247_ = _031_;
  assign _084_ = count[1];
  assign _083_ = count[0];
  assign _085_ = count[2];
  assign _086_ = count[3];
  assign _248_ = _032_;
  assign _246_ = _030_;
  assign _020_ = Q[0];
  assign _029_ = Q_minus_1;
  assign _244_ = state[3];
  assign _242_ = state[1];
  assign _249_ = _033_;
  assign _250_ = _034_;
  assign _087_ = count[4];
  assign _096_ = multiplier[0];
  assign _021_ = Q[1];
  assign _097_ = multiplier[1];
  assign _022_ = Q[2];
  assign _098_ = multiplier[2];
  assign _023_ = Q[3];
  assign _099_ = multiplier[3];
  assign _024_ = Q[4];
  assign _100_ = multiplier[4];
  assign _025_ = Q[5];
  assign _101_ = multiplier[5];
  assign _026_ = Q[6];
  assign _102_ = multiplier[6];
  assign _027_ = Q[7];
  assign _103_ = multiplier[7];
  assign _028_ = Q[8];
  assign _003_ = A[0];
  assign _004_ = A[1];
  assign _012_ = M[0];
  assign _005_ = A[2];
  assign _013_ = M[1];
  assign _006_ = A[3];
  assign _014_ = M[2];
  assign _015_ = M[3];
  assign _386_ = _035_;
  assign _387_ = _036_;
  assign _388_ = _037_;
  assign _389_ = _038_;
  assign _390_ = _039_;
  assign _391_ = _040_;
  assign _392_ = _041_;
  assign _393_ = _042_;
  assign _394_ = _043_;
  assign _395_ = _044_;
  assign _396_ = _045_;
  assign _397_ = _046_;
  assign _398_ = _047_;
  assign _399_ = _048_;
  assign _224_ = product[0];
  assign _400_ = _049_;
  assign _231_ = product[1];
  assign _401_ = _050_;
  assign _232_ = product[2];
  assign _402_ = _051_;
  assign _233_ = product[3];
  assign _403_ = _052_;
  assign _234_ = product[4];
  assign _404_ = _053_;
  assign _235_ = product[5];
  assign _405_ = _054_;
  assign _236_ = product[6];
  assign _406_ = _055_;
  assign _237_ = product[7];
  assign _407_ = _056_;
  assign _238_ = product[8];
  assign _408_ = _057_;
  assign _239_ = product[9];
  assign _409_ = _058_;
  assign _225_ = product[10];
  assign _410_ = _059_;
  assign _226_ = product[11];
  assign _411_ = _060_;
  assign _227_ = product[12];
  assign _412_ = _061_;
  assign _228_ = product[13];
  assign _413_ = _062_;
  assign _229_ = product[14];
  assign _414_ = _063_;
  assign _230_ = product[15];
  assign _415_ = _064_;
  assign _416_ = _065_;
  assign _417_ = _066_;
  assign _418_ = _067_;
  assign _419_ = _068_;
  assign _420_ = _069_;
  assign _421_ = _070_;
  assign _422_ = _071_;
  assign _423_ = _072_;
  assign _424_ = _073_;
  assign _088_ = multiplicand[0];
  assign _425_ = _074_;
  assign _089_ = multiplicand[1];
  assign _426_ = _075_;
  assign _090_ = multiplicand[2];
  assign _427_ = _076_;
  assign _091_ = multiplicand[3];
  assign _428_ = _077_;
  assign _092_ = multiplicand[4];
  assign _429_ = _078_;
  assign _093_ = multiplicand[5];
  assign _430_ = _079_;
  assign _094_ = multiplicand[6];
  assign _431_ = _080_;
  assign _095_ = multiplicand[7];
  assign _432_ = _081_;
  assign _433_ = _082_;
endmodule
