/* Generated by Yosys 0.57+148 (git sha1 259bd6fb3, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

(* top =  1  *)
(* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/counter_opt2.v:1.1-13.10" *)
module counter_opt2(clk, reset, q);
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/counter_opt2.v:1.28-1.31" *)
  input clk;
  wire clk;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/counter_opt2.v:1.40-1.45" *)
  input reset;
  wire reset;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/counter_opt2.v:1.55-1.56" *)
  output q;
  wire q;
  wire _00_;
  wire _01_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/counter_opt2.v:10.12-10.21|/usr/local/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire _02_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/counter_opt2.v:10.12-10.21|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire _03_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/counter_opt2.v:10.12-10.21|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/counter_opt2.v:2.11-2.16" *)
  wire _08_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/counter_opt2.v:2.11-2.16" *)
  wire _09_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/counter_opt2.v:2.11-2.16" *)
  wire _10_;
  wire _11_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/counter_opt2.v:1.55-1.56" *)
  wire _12_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/counter_opt2.v:1.40-1.45" *)
  wire _13_;
  (* force_downto = 32'd1 *)
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/counter_opt2.v:10.12-10.21|/usr/local/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [2:0] _14_;
  (* force_downto = 32'd1 *)
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/counter_opt2.v:10.12-10.21|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [2:0] _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/counter_opt2.v:2.11-2.16" *)
  wire [2:0] count;
  sky130_fd_sc_hd__clkinv_1 _19_ (
    .A(_08_),
    .Y(_02_)
  );
  sky130_fd_sc_hd__clkinv_1 _20_ (
    .A(_13_),
    .Y(_05_)
  );
  sky130_fd_sc_hd__nor3b_1 _21_ (
    .A(_08_),
    .B(_09_),
    .C_N(_10_),
    .Y(_12_)
  );
  sky130_fd_sc_hd__nand2_1 _22_ (
    .A(_08_),
    .B(_09_),
    .Y(_11_)
  );
  sky130_fd_sc_hd__xor2_1 _23_ (
    .A(_08_),
    .B(_09_),
    .X(_03_)
  );
  sky130_fd_sc_hd__xnor2_1 _24_ (
    .A(_10_),
    .B(_11_),
    .Y(_04_)
  );
  sky130_fd_sc_hd__clkinv_1 _25_ (
    .A(_13_),
    .Y(_06_)
  );
  sky130_fd_sc_hd__clkinv_1 _26_ (
    .A(_13_),
    .Y(_07_)
  );
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/counter_opt2.v:5.1-11.4" *)
  sky130_fd_sc_hd__dfrtp_1 _27_ (
    .CLK(clk),
    .D(_14_[0]),
    .Q(count[0]),
    .RESET_B(_16_)
  );
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/counter_opt2.v:5.1-11.4" *)
  sky130_fd_sc_hd__dfrtp_1 _28_ (
    .CLK(clk),
    .D(_15_[1]),
    .Q(count[1]),
    .RESET_B(_17_)
  );
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/counter_opt2.v:5.1-11.4" *)
  sky130_fd_sc_hd__dfrtp_1 _29_ (
    .CLK(clk),
    .D(_15_[2]),
    .Q(count[2]),
    .RESET_B(_18_)
  );
  assign _15_[0] = _14_[0];
  assign _14_[2:1] = count[2:1];
  assign _08_ = count[0];
  assign _14_[0] = _02_;
  assign _09_ = count[1];
  assign _10_ = count[2];
  assign q = _12_;
  assign _15_[1] = _03_;
  assign _15_[2] = _04_;
  assign _13_ = reset;
  assign _16_ = _05_;
  assign _17_ = _06_;
  assign _18_ = _07_;
endmodule
