/* Generated by Yosys 0.57+148 (git sha1 259bd6fb3, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

(* top =  1  *)
(* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/counter_opt.v:1.1-13.10" *)
module counter_opt(clk, en, reset, q);
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/counter_opt.v:1.27-1.30" *)
  input clk;
  wire clk;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/counter_opt.v:1.39-1.41" *)
  input en;
  wire en;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/counter_opt.v:1.49-1.54" *)
  input reset;
  wire reset;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/counter_opt.v:1.64-1.65" *)
  output q;
  wire q;
  wire _00_;
  wire _01_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/counter_opt.v:2.11-2.16" *)
  wire _02_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/counter_opt.v:1.39-1.41" *)
  wire _03_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/counter_opt.v:1.49-1.54" *)
  wire _04_;
  (* force_downto = 32'd1 *)
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/counter_opt.v:10.12-10.21|/usr/local/bin/../share/yosys/techmap.v:270.23-270.24" *)
  (* unused_bits = "1 2 3" *)
  wire [3:0] _05_;
  wire _06_;
  wire _07_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/counter_opt.v:2.11-2.16" *)
  (* unused_bits = "1 2 3" *)
  wire [3:0] count;
  sky130_fd_sc_hd__clkinv_1 _08_ (
    .A(_04_),
    .Y(_00_)
  );
  sky130_fd_sc_hd__xor2_1 _09_ (
    .A(_02_),
    .B(_03_),
    .X(_01_)
  );
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/counter_opt.v:5.1-11.4" *)
  sky130_fd_sc_hd__dfrtp_1 _10_ (
    .CLK(clk),
    .D(_07_),
    .Q(count[0]),
    .RESET_B(_06_)
  );
  assign _05_[3:1] = count[3:1];
  assign q = count[0];
  assign _02_ = count[0];
  assign _03_ = en;
  assign _07_ = _01_;
  assign _04_ = reset;
  assign _06_ = _00_;
endmodule
