/* Generated by Yosys 0.57+148 (git sha1 259bd6fb3, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

(* top =  1  *)
(* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/dff_const4.v:1.1-18.10" *)
module dff_const4(clk, reset, q);
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/dff_const4.v:1.25-1.28" *)
  input clk;
  wire clk;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/dff_const4.v:1.36-1.41" *)
  input reset;
  wire reset;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/dff_const4.v:1.54-1.55" *)
  output q;
  wire q;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/dff_const4.v:2.5-2.7" *)
  wire q1;
  assign q = 1'h1;
  assign q1 = 1'h1;
endmodule
