/* Generated by Yosys 0.57+148 (git sha1 259bd6fb3, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

(* top =  1  *)
(* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/dff_const5.v:2.1-19.10" *)
module dff_const5(clk, reset, q);
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/dff_const5.v:2.25-2.28" *)
  input clk;
  wire clk;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/dff_const5.v:2.36-2.41" *)
  input reset;
  wire reset;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/dff_const5.v:2.54-2.55" *)
  output q;
  wire q;
  wire _0_;
  wire _1_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/dff_const5.v:2.36-2.41" *)
  wire _2_;
  wire _3_;
  wire _4_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/dff_const5.v:3.5-3.7" *)
  wire q1;
  sky130_fd_sc_hd__clkinv_1 _5_ (
    .A(_2_),
    .Y(_0_)
  );
  sky130_fd_sc_hd__clkinv_1 _6_ (
    .A(_2_),
    .Y(_1_)
  );
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/dff_const5.v:5.1-17.4" *)
  sky130_fd_sc_hd__dfrtp_1 _7_ (
    .CLK(clk),
    .D(q1),
    .Q(q),
    .RESET_B(_3_)
  );
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/dff_const5.v:5.1-17.4" *)
  sky130_fd_sc_hd__dfrtp_1 _8_ (
    .CLK(clk),
    .D(1'h1),
    .Q(q1),
    .RESET_B(_4_)
  );
  assign _2_ = reset;
  assign _3_ = _0_;
  assign _4_ = _1_;
endmodule
