/* Generated by Yosys 0.57+148 (git sha1 259bd6fb3, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

(* top =  1  *)
(* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/multiple_module_opt2.v:8.1-17.10" *)
module multiple_module_opt2(a, b, c, d, y);
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/multiple_module_opt2.v:8.35-8.36" *)
  input a;
  wire a;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/multiple_module_opt2.v:8.45-8.46" *)
  input b;
  wire b;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/multiple_module_opt2.v:8.55-8.56" *)
  input c;
  wire c;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/multiple_module_opt2.v:8.65-8.66" *)
  input d;
  wire d;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/multiple_module_opt2.v:8.76-8.77" *)
  output y;
  wire y;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/multiple_module_opt2.v:2.46-2.47" *)
  wire _0_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/multiple_module_opt2.v:8.35-8.36" *)
  wire _1_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/multiple_module_opt2.v:8.45-8.46" *)
  wire _2_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/multiple_module_opt2.v:8.55-8.56" *)
  wire _3_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/multiple_module_opt2.v:8.65-8.66" *)
  wire _4_;
  (* hdlname = "U1 a" *)
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/multiple_module_opt2.v:2.25-2.26" *)
  wire \U1.a ;
  (* hdlname = "U1 b" *)
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/multiple_module_opt2.v:2.35-2.36" *)
  wire \U1.b ;
  (* hdlname = "U1 y" *)
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/multiple_module_opt2.v:2.46-2.47" *)
  wire \U1.y ;
  (* hdlname = "U2 a" *)
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/multiple_module_opt2.v:2.25-2.26" *)
  wire \U2.a ;
  (* hdlname = "U2 b" *)
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/multiple_module_opt2.v:2.35-2.36" *)
  wire \U2.b ;
  (* hdlname = "U2 y" *)
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/multiple_module_opt2.v:2.46-2.47" *)
  wire \U2.y ;
  (* hdlname = "U3 a" *)
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/multiple_module_opt2.v:2.25-2.26" *)
  wire \U3.a ;
  (* hdlname = "U3 b" *)
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/multiple_module_opt2.v:2.35-2.36" *)
  wire \U3.b ;
  (* hdlname = "U3 y" *)
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/multiple_module_opt2.v:2.46-2.47" *)
  wire \U3.y ;
  (* hdlname = "U4 a" *)
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/multiple_module_opt2.v:2.25-2.26" *)
  wire \U4.a ;
  (* hdlname = "U4 b" *)
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/multiple_module_opt2.v:2.35-2.36" *)
  wire \U4.b ;
  (* hdlname = "U4 y" *)
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/multiple_module_opt2.v:2.46-2.47" *)
  wire \U4.y ;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/multiple_module_opt2.v:9.6-9.8" *)
  wire n1;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/multiple_module_opt2.v:9.9-9.11" *)
  wire n2;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/multiple_module_opt2.v:9.12-9.14" *)
  wire n3;
  assign \U4.a  = n3;
  assign \U4.b  = n1;
  assign y = \U4.y ;
  assign \U3.a  = n2;
  assign \U3.b  = d;
  assign n3 = \U3.y ;
  assign \U2.a  = b;
  assign \U2.b  = c;
  assign n2 = \U2.y ;
  assign \U1.a  = a;
  assign \U1.b  = 1'h0;
  assign n1 = \U1.y ;
  assign _0_ = 1'h0;
  assign _1_ = a;
  assign _3_ = c;
  assign _2_ = b;
  assign _4_ = d;
  assign \U4.y  = _0_;
endmodule
