/* Generated by Yosys 0.57+148 (git sha1 259bd6fb3, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

(* top =  1  *)
(* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/multiple_module_opt2.v:8.1-17.10" *)
module multiple_module_opt2(a, b, c, d, y);
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/multiple_module_opt2.v:8.35-8.36" *)
  input a;
  wire a;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/multiple_module_opt2.v:8.45-8.46" *)
  input b;
  wire b;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/multiple_module_opt2.v:8.55-8.56" *)
  input c;
  wire c;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/multiple_module_opt2.v:8.65-8.66" *)
  input d;
  wire d;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/multiple_module_opt2.v:8.76-8.77" *)
  output y;
  wire y;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/multiple_module_opt2.v:8.35-8.36" *)
  wire _0_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/multiple_module_opt2.v:8.45-8.46" *)
  wire _1_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/multiple_module_opt2.v:8.55-8.56" *)
  wire _2_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/multiple_module_opt2.v:8.65-8.66" *)
  wire _3_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/multiple_module_opt2.v:8.76-8.77" *)
  wire _4_;
  (* hdlname = "U1 y" *)
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/multiple_module_opt2.v:2.46-2.47" *)
  wire \U1.y ;
  (* hdlname = "U2 y" *)
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/multiple_module_opt2.v:2.46-2.47" *)
  wire \U2.y ;
  (* hdlname = "U3 y" *)
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/multiple_module_opt2.v:2.46-2.47" *)
  wire \U3.y ;
  assign _4_ = 1'h0;
  assign _0_ = a;
  assign _2_ = c;
  assign _1_ = b;
  assign _3_ = d;
  assign y = _4_;
endmodule
