/* Generated by Yosys 0.57+148 (git sha1 259bd6fb3, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

(* top =  1  *)
(* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/multiple_module_opt.v:11.1-21.10" *)
module multiple_module_opt(a, b, c, d, y);
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/multiple_module_opt.v:11.34-11.35" *)
  input a;
  wire a;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/multiple_module_opt.v:11.44-11.45" *)
  input b;
  wire b;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/multiple_module_opt.v:11.54-11.55" *)
  input c;
  wire c;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/multiple_module_opt.v:11.64-11.65" *)
  input d;
  wire d;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/multiple_module_opt.v:11.75-11.76" *)
  output y;
  wire y;
  wire _0_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/multiple_module_opt.v:11.34-11.35" *)
  wire _1_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/multiple_module_opt.v:11.44-11.45" *)
  wire _2_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/multiple_module_opt.v:11.54-11.55" *)
  wire _3_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/multiple_module_opt.v:11.75-11.76" *)
  wire _4_;
  (* hdlname = "U1 y" *)
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/multiple_module_opt.v:1.47-1.48" *)
  wire \U1.y ;
  sky130_fd_sc_hd__a21o_1 _5_ (
    .A1(_2_),
    .A2(_1_),
    .B1(_3_),
    .X(_4_)
  );
  assign _2_ = b;
  assign _3_ = c;
  assign y = _4_;
  assign _1_ = a;
endmodule
