/* Generated by Yosys 0.57+148 (git sha1 259bd6fb3, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

(* top =  1  *)
(* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/opt_check3.v:2.1-4.10" *)
module opt_check3(a, b, c, y);
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/opt_check3.v:2.26-2.27" *)
  input a;
  wire a;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/opt_check3.v:2.36-2.37" *)
  input b;
  wire b;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/opt_check3.v:2.45-2.46" *)
  input c;
  wire c;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/opt_check3.v:2.56-2.57" *)
  output y;
  wire y;
  wire _0_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/opt_check3.v:2.26-2.27" *)
  wire _1_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/opt_check3.v:2.36-2.37" *)
  wire _2_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/opt_check3.v:2.45-2.46" *)
  wire _3_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/opt_check3.v:2.56-2.57" *)
  wire _4_;
  sky130_fd_sc_hd__and3_1 _5_ (
    .A(_2_),
    .B(_3_),
    .C(_1_),
    .X(_4_)
  );
  assign _2_ = b;
  assign _3_ = c;
  assign _1_ = a;
  assign y = _4_;
endmodule
