/* Generated by Yosys 0.57+148 (git sha1 259bd6fb3, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

(* top =  1  *)
(* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/opt_check.v:1.1-6.10" *)
module opt_check(a, b, c, y1, y2);
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/opt_check.v:1.25-1.26" *)
  input a;
  wire a;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/opt_check.v:1.35-1.36" *)
  input b;
  wire b;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/opt_check.v:1.45-1.46" *)
  input c;
  wire c;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/opt_check.v:1.56-1.58" *)
  output y1;
  wire y1;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/opt_check.v:1.67-1.69" *)
  output y2;
  wire y2;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/opt_check.v:1.25-1.26" *)
  wire _0_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/opt_check.v:1.35-1.36" *)
  wire _1_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/opt_check.v:1.45-1.46" *)
  wire _2_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/opt_check.v:1.56-1.58" *)
  wire _3_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/opt_check.v:1.67-1.69" *)
  wire _4_;
  sky130_fd_sc_hd__clkinv_1 _5_ (
    .A(_2_),
    .Y(_4_)
  );
  sky130_fd_sc_hd__and2_0 _6_ (
    .A(_1_),
    .B(_0_),
    .X(_3_)
  );
  assign _2_ = c;
  assign y2 = _4_;
  assign _1_ = b;
  assign _0_ = a;
  assign y1 = _3_;
endmodule
