/* Generated by Yosys 0.57+148 (git sha1 259bd6fb3, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

(* top =  1  *)
(* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/opt_check4.v:1.1-3.11" *)
module opt_check4(a, b, c, y);
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/opt_check4.v:1.26-1.27" *)
  input a;
  wire a;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/opt_check4.v:1.36-1.37" *)
  input b;
  wire b;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/opt_check4.v:1.46-1.47" *)
  input c;
  wire c;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/opt_check4.v:1.57-1.58" *)
  output y;
  wire y;
  wire _0_;
  wire _1_;
  wire _2_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/opt_check4.v:1.26-1.27" *)
  wire _3_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/opt_check4.v:1.36-1.37" *)
  wire _4_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/opt_check4.v:1.46-1.47" *)
  wire _5_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/opt_check4.v:1.57-1.58" *)
  wire _6_;
  sky130_fd_sc_hd__xnor2_1 _7_ (
    .A(_5_),
    .B(_3_),
    .Y(_6_)
  );
  assign _5_ = c;
  assign _3_ = a;
  assign _4_ = b;
  assign y = _6_;
endmodule
