/* Generated by Yosys 0.57+148 (git sha1 259bd6fb3, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

(* top =  1  *)
(* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/opt_check2.v:1.1-3.10" *)
module opt_check2(a, b, y);
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/opt_check2.v:1.26-1.27" *)
  input a;
  wire a;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/opt_check2.v:1.36-1.37" *)
  input b;
  wire b;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/opt_check2.v:1.47-1.48" *)
  output y;
  wire y;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/opt_check2.v:1.26-1.27" *)
  wire _0_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/opt_check2.v:1.36-1.37" *)
  wire _1_;
  (* src = "/home/ank/Desktop/SoC_Shwetank/verilog_files/opt_check2.v:1.47-1.48" *)
  wire _2_;
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _3_ (
    .A(_0_),
    .SLEEP(_1_),
    .X(_2_)
  );
  assign _0_ = a;
  assign _1_ = b;
  assign y = _2_;
endmodule
